ci-config:
  - changed-files:
      - any-glob-to-any-file: .github/*
auth:
  - changed-files:
      - any-glob-to-any-file: common/auth/*
core:
  - changed-files:
      - any-glob-to-any-file: common/core/*
design:
  - changed-files:
      - any-glob-to-any-file: common/design/*
translations:
  - changed-files:
      - any-glob-to-any-file: common/translations/*
account:
  - changed-files:
      - any-glob-to-any-file: features/account/*
lessons-data:
  - changed-files:
      - any-glob-to-any-file: common/lessons-data/*
settings:
  - changed-files:
      - any-glob-to-any-file: features/settings/*
app-widgets:
  - changed-files:
      - any-glob-to-any-file: features/app-widgets/*
media:
  - changed-files:
      - any-glob-to-any-file: libraries/media/*
pdf:
  - changed-files:
      - any-glob-to-any-file: features/pdf/*
dependencies:
  - changed-files:
      - any-glob-to-any-file: '**/*.toml'
tv-app:
  - changed-files:
      - any-glob-to-any-file: app-tv/*
block-kit:
  - changed-files:
      - any-glob-to-any-file: libraries/block-kit/*