ci:
  - '.github/*'
auth:
  - 'common/auth/*'
core:
  - 'common/core/*'
design:
  - 'common/design/*'
translations:
  - 'common/translations/*'
account:
  - 'features/account/*'
bible:
  - 'features/bible/*'
lessons:
  - 'features/lessons/*'
lessons-data:
  - 'common/lessons-data/*'
reader:
  - 'features/reader/*'
settings:
  - 'features/settings/*'
app-widgets:
  - 'features/app-widgets/*'
media:
  - 'features/media/*'
pdf:
  - 'features/pdf/*'
dependencies:
  - 'buildSrc/src/main/kotlin/dependencies/*'
test:
  - any: ['*/src/test/*','*/src/androidTest/*']
testing:
  - 'libraries/test_utils/*'
gradle:
  - all: ['*.gradle.kts']
layouts:
  - any: ['*.xml']