#
# Copyright (c) 2023. Adventech <info@adventech.io>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
PSPDFKIT_LICENSE=b0qUi6gbdNdpC3Z0-pteQOq6p7opt_2oFC6OXcLEMpze6zSJjUM-yaakE_ZENcy2IjT-IyvoSdPfFU6pAWGjErBvEvlwp0vL6kqEo6JlSDdSKVH7GiXQtPay-HPKsXwTE0ethyHHT65IAF5NzaK8qVyQ9LWuA2sjhh15ixzwjVCWkdJ3gU_FfYhWEEMZuOluvr5jhouaA_2etvk69dxX7yLOKpLxlHPDCX5Eb_vy8EBmubGK9bOS4HBmMcz72zub6-IZSuJsig0V1STOJVFDc6-b6Qm8TojhZS4_fOlPFwGZOsGs-jcgqfSY9-8_wmnSkxh7IktNsImQRr9eG589IeehxcwXGf6syMRFjtpY8roI7Jy8Wz_A_9kqrb6ZiUVE9QVBwKtujJMe90r1IYYuFm4mTOpugyX88pKZFTGNxbTmdUsg_5lqysvXANwzpnTCwc_R_MQGViOqLX-C7rULrB9154uWJWSMlXI4x9K6O6VyAGamg696S420ys-vh0dOOmZW9tbP_Y7WfHU9k-AVfCk7C7OxwuPdZhqeKwSsclXdiLszjc6k7jeNPiBtayP3NVnrrGo8u3GxowIfX5_JPfAcsTBJDJDXTL0jU_MkkfQ=
WEB_CLIENT_ID=443920152945-rgptd4sa4vqv7qlpq070pq9pifv48k1j.apps.googleusercontent.com