name: Release Management

on:
  push:
    branches:
      - develop

jobs:
  update_draft_release:
    runs-on: macos-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  submit-release:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Decrypt secrets
        run: ./release/decrypt-secrets.sh
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Add Embrace config
        env:
          FIREBASE_CONFIG: ${{ secrets.EMBRACE_CONFIG }}
        run: |
          echo $EMBRACE_CONFIG > app/src/main/embrace-config.json

      - name: Generate build number
        run: echo "BUILD_NUMBER=${{github.run_number}}" > release/build_number.properties

      - name: Build Release
        run: ./gradlew app:bundleRelease --stacktrace

      - name: Publish to Internal track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: release/play-account.json
          packageName: com.cryart.sabbathschool
          track: internal
          status: completed
          whatsNewDirectory: distribution/whatsnew
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - name: Publish to TV Internal track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: release/play-account.json
          packageName: com.cryart.sabbathschool
          track: tv:internal
          status: completed
          whatsNewDirectory: distribution/whatsnew
          releaseFiles: app-tv/build/outputs/bundle/release/app-tv-release.aab
          mappingFile: app-tv/build/outputs/mapping/release/mapping.txt